{% set name = "pytsql" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytsql-{{ version }}.tar.gz
  sha256: 58c0c007d55dfdc5c7a34870206d3fd06b4c9f1dc6d836b8ee8d064a7955ab0a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - antlr-python-runtime =4.9.2
    - pyodbc >=4.0.30
    - python
    - sqlalchemy >=1.4

test:
  imports:
    - pytsql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytsql/
  summary: pytsql allows to run mssql scripts, typically run via GUIs, via CLI.
  dev_url: https://github.com/quantco/pytsql
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
    - kklein
